version: '3'

services:

  tests:
    build: ./tests
    command: echo Ready!
    depends_on:
      - lutece

  lutece:
    build: ./lutece
    ports:
      - "8081:8080"
    depends_on:
      - storage

  storage:
    build: ./mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=motdepasse
