instances:
  lutece_0:
    configuration: {}
    definition: lutece
    service_providers:
    - mysql_0
  mysql_0:
    configuration:
      version: 57
    definition: mysql
    service_providers: []
